services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-staff
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend-staff
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-staff:/data/db

  staff-svc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: staff-svc
    environment:
      - PORT=3007
      - MONGOADMIN=${MONGOADMIN}
      - MONGOPASS=${MONGOPASS}
      - MONGOURL=${MONGOURL}
      - NODE_ENV=production
      - API_PREFIX=/api/v1
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SVC=${AUTH_SVC}
      - KAFKA_HOST=${KAFKA_HOST}
    depends_on:
      - mongodb
    networks:
      - backend-staff
    ports:
      - "3007:3007"

volumes:
  mongo-data-staff:

networks:
  backend-staff:
    driver: bridge
