openapi: 3.0.0
info:
  title: Staff Service
  version: 1.0.0
  description: API to manage doctors in a clinic

servers:
  - url: http://localhost:3001
    description: Local server

tags:
  - name: staff
    description: Operations about doctors

paths:
/staff/clinic/{clinic}/speciality/{speciality}:
  get:
    summary: Get doctors by speciality in a clinic
    parameters:
      - in: path
        name: clinic
        required: true
        schema:
          type: string
      - in: path
        name: speciality
        required: false
        schema:
          type: string
    responses:
      '200':
        description: List of doctors
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Doctor'
      '404':
        description: No doctors found
      '400':
        description: Invalid input
/staff/{doctorId}:
  put:
    summary: Update a doctor's specialty
    parameters:
      - in: path
        name: doctorId
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              specialty:
                type: string
    responses:
      '200':
        description: Specialty updated successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                doctor:
                  $ref: '#/components/schemas/Doctor'
      '404':
        description: Doctor not found
      '400':
        description: Invalid input
  /staff/register:
    post:
      summary: Register a new doctor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                surname:
                  type: string
                specialty:
                  type: string
                dni:
                  type: string
                clinic:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: Doctor created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Doctor'
        '400':
          description: Invalid input

  /staff/{doctorId}:
    delete:
      summary: Delete a doctor by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Doctor deleted successfully
        '404':
          description: Doctor not found
        '400':
          description: Invalid ID supplied

components:
  # Aquí irán tus componentes reutilizables
