apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: staff-svc
  name: staff-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: staff-svc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: staff-svc
    spec:
      containers:
        - env:
            - name: API_PREFIX
              value: /api/v1
            - name: AUTH_SVC
              valueFrom:
                secretKeyRef:
                  name: staff-secrets
                  key: AUTH_SVC
            - name: PAYMENT_SVC
              valueFrom:
                secretKeyRef:
                  name: staff-secrets
                  key: PAYMENT_SVC
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: staff-secrets
                  key: JWT_SECRET
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: staff-secrets
                  key: KAFKA_HOST
            - name: MONGOURL
              valueFrom:
                secretKeyRef:
                  name: staff-secrets
                  key: MONGOURL
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3007"
          image: ghcr.io/fis2425/staff:latest
          name: staff-svc
          ports:
            - containerPort: 3007
              protocol: TCP
      restartPolicy: Always
